### ISSUE TITLE
Getting `invalid account data for instruction` on sample code

### ISSUE THREAD

**Issue by metaproph3t** [solana-foundation/anchor#2743]
Hello there!

For some reason, I'm intermittently getting errors when running `anchor test` on the untouched code that's created by anchor init. [Michael has run into the same error](https://discord.com/channels/889577356681945098/889577399308656662/1155186444701282304). When I logged the errors, this is what I got:
```
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction
    at Connection.sendEncodedTransaction (/home/user/picobook/node_modules/@solana/web3.js/src/connection.ts:5922:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Connection.sendRawTransaction (/home/user/picobook/node_modules/@solana/web3.js/src/connection.ts:5881:20)
    at sendAndConfirmRawTransaction (/home/user/picobook/node_modules/@coral-xyz/anchor/src/provider.ts:370:21)
    at AnchorProvider.sendAndConfirm (/home/user/picobook/node_modules/@coral-xyz/anchor/src/provider.ts:160:14)
    at MethodsBuilder.rpc [as _rpcFn] (/home/user/picobook/node_modules/@coral-xyz/anchor/src/program/namespace/rpc.ts:29:16) {
  logs: [
    'Program Cm1pi42PSyi6sVRMUJvaLyBGtU9cBNw4ciXCxNr1UPn5 invoke [1]',
    'Program is not deployed',
    'Program Cm1pi42PSyi6sVRMUJvaLyBGtU9cBNw4ciXCxNr1UPn5 failed: invalid account data for instruction'
  ],
  programErrorStack: ProgramErrorStack {
    stack: [
      [PublicKey [PublicKey(Cm1pi42PSyi6sVRMUJvaLyBGtU9cBNw4ciXCxNr1UPn5)]]
    ]
  }
}
```

So it appears the program isn't getting deployed to the test validator. I'm using Anchor 0.29.0, Solana 0.17.0, and I'm on a GNU/Linux machine.

**Comment by acheroncrypto** [comment]
This could happen if the test validator couldn't get started in in time as the default maximum wait time for the initialization is 5 seconds. Try adding

```toml
[test]
startup_wait = 10000
```

in your `Anchor.toml` to see if that makes a difference.

**Comment by metaproph3t** [comment]
still getting the error with that in my Anchor.toml

**Comment by acheroncrypto** [comment]
What's the name of the program?

**Comment by metaproph3t** [comment]
picobook

**Comment by acheroncrypto** [comment]
The issue is not with the name then. A reproducable example setup would help debug this — are you able to reproduce this in 
Docker or GitHub CI?

**Comment by metaproph3t** [comment]
I've just tested it in a GitHub action and it seems to pass there :(

**Comment by solsolomon** [comment]
Same is happening to me with any projects created recently from anchor init. All the old projects work fine.
